- type: job
  id: CargoTrainee
  name: job-name-cargotrainee
  description: job-description-cargotrainee
  playTimeTracker: JobCargoTrainee
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 18000 #5 hrs
      inverted: true # stop playing trainee if you're good at cargo!
  startingGear: CargoTraineeGear
  icon: "JobIconCargoTrainee"
  supervisors: job-supervisors-cargo
  canBeAntag: false
  access:
  - Cargo
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard

- type: startingGear
  id: CargoTraineeGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: CargoTraineePDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    # we don't have an ingame cargo guidebook yet...
    # pocket2: (whatever a potential future cargo guidebook is called)
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: CargoTraineeChameleonOutfit
  job: CargoTrainee
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterCargo
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesFingerless
