- type: entity
  id: LockerBoozeFilled # For the standard bar
  suffix: Filled
  parent: LockerBooze
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBooze

- type: entityTable
  id: FillLockerBooze
  table: !type:AllSelector
    children:
    # Normal bartending gear
    - id: ClothingEyesHudBeer
    - id: DrinkBeerBottleFull
      amount: !type:BinomialNumberSelector
        trials: 3
    - id: DrinkShaker
    - id: HandLabeler
    - id: RagItem
      amount: 2
    # Nonlethal armaments, for defending the bar from animals and rowdy customers and whatnot
    - id: ClothingOuterArmorBasicSlim
    - id: WeaponShotgunDoubleBarreledRubber
    - id: BoxBeanbag
      amount: 2

- type: entity
  id: LockerBoozeFilledMaints # For the maints bar; randomized contents to represent that it's been used and abandoned
  suffix: Maints, Filled
  parent: LockerBooze
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBoozeMaints

- type: entityTable
  id: FillLockerBoozeMaints
  table: !type:AllSelector
    children:
    - !type:NestedSelector
      tableId: MaintBarStandardTable
      rolls: !type:BinomialNumberSelector # This sometimes results in duplicate items, unfortunately
        trials: 5
    - !type:NestedSelector
      tableId: MaintBarArmorTable
      prob: 0.20
    - !type:NestedSelector
      tableId: MaintBarShotgunTable
      prob: 0.1 # Slightly higher chance than finding weapons in normal maints lockers, since this is a more "specific" locker (and one with a lock on it)
    - !type:NestedSelector
      tableId: MaintBarShotgunAmmoTable
      prob: 0.05

- type: entityTable
  id: MaintBarStandardTable # For the maints bar; randomly spawns one piece of normal bartending gear. We exclude the beer goggles since they're a thief objective and this makes it too easy.
  table: !type:GroupSelector
    children:
    - id: DrinkBeerBottleFull
    - id: DrinkShaker
    - id: HandLabeler
    - id: RagItem

- type: entityTable
  id: MaintBarArmorTable # For the maints bar; randomly spawns one piece of armor
  table: !type:GroupSelector
    children:
    - id: ClothingOuterArmorBasicSlim

- type: entityTable
  id: MaintBarShotgunTable # For the maints bar; randomly spawns either the normal bar shotgun or a firearm with lethal rounds
  table: !type:GroupSelector
    children:
    - id: WeaponShotgunDoubleBarreledRubber
      weight: 95
    - !type:GroupSelector # Lethal shotguns
      weight: 5
      children:
      - id: WeaponShotgunDoubleBarreled
      - id: WeaponShotgunSawn

- type: entityTable
  id: MaintBarShotgunAmmoTable # For the maints bar; randomly spawns either the normal box of beanbag shells or a more exotic ammo type
  table: !type:GroupSelector
    children:
    - id: BoxBeanbag
      weight: 95
    - !type:GroupSelector
      weight: 5
      children:
      - id: BoxLethalshot
      - id: BoxShotgunFlare
      - id: BoxShotgunPractice
      - id: BoxShellTranquilizer

#- type: entity
#  id: LockerFormalFilled
#  suffix: Filled
#  parent: LockerFormal

- type: entity
  id: ClosetChefFilled
  suffix: Filled
  parent: ClosetChef
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetChef

- type: entityTable
  id: FillClosetChef
  table: !type:AllSelector
    children:
    - id: VariantCubeBox
    - id: SprayBottleWater
    - id: FoodBoxCloth
    - id: ReagentContainerSugar
    - id: FoodCondimentBottleEnzyme
    - id: DrinkSoyMilkCarton
    - !type:AllSelector
      rolls: 2
      children:
      - id: DrinkMilkCarton
      # really, milk should go in the fridge. Unfortunately saltern only has freezers.
      # yes, I'm using this as an excuse to not have to do extra work.
      - id: ReagentContainerFlour
      - id: BoxMousetrap
    - !type:AllSelector
      rolls: 3
      children:
      - id: FoodCondimentPacketSalt
      - id: FoodCondimentPacketPepper

- type: entity
  id: ClosetJanitorFilled
  suffix: Filled
  parent: ClosetJanitor
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetJanitor

- type: entityTable
  id: FillClosetJanitor
  table: !type:AllSelector
    children:
    - id: WetFloorSign
      amount: 3
    - id: LightReplacer
    - id: BoxLightMixed
    - id: Holoprojector
    - !type:AllSelector
      rolls: 2
      children:
      - id: MopItem
      - id: BoxMousetrap
      - id: TrashBag
      - id: SoapNT
      - id: FlashlightLantern
      - id: Plunger
      - id: WireBrush

- type: entity
  id: ClosetLegalFilled
  suffix: Filled
  parent: ClosetLegal
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetLegal

- type: entityTable
  id: FillClosetLegal
  table: !type:AllSelector
    children:
    - id: BriefcaseBrownFilled
      prob: 0.80
    - id: ClothingOuterRobesJudge

- type: entity
  id: LockerBotanistFilled
  suffix: Filled
  parent: LockerBotanist
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBotanist

- type: entityTable
  id: FillLockerBotanist
  table: !type:AllSelector
    children:
    - id: ClothingHandsGlovesLeather
    - id: ClothingOuterApronBotanist
    - id: ClothingHeadBandBotany
    - id: ChemistryBottleRobustHarvest
      prob: 0.3
    - id: ClothingBeltPlant
    - id: PlantBag ##Some maps don't have nutrivend
    - id: BoxMouthSwab
    - id: Dropper
    - id: HandLabeler
    - id: ClothingUniformOveralls
    - id: ClothingHeadHatTrucker
      prob: 0.1

- type: entity
  id: LockerBotanistLoot
  suffix: Loot
  parent: LockerBotanist
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBotanistLoot

- type: entityTable
  id: FillLockerBotanistLoot
  table: !type:AllSelector
    children:
    - id: ClothingUniformOveralls
    - id: ClothingHeadHatTrucker
      prob: 0.3
    - id: GatfruitSeeds
      prob: 0.1
    - id: FlyAmanitaSeeds
      prob: 0.5
    - id: NettleSeeds
      prob: 0.7

- type: entity
  id: ClosetJanitorBombFilled
  parent: ClosetJanitorBomb
  suffix: DO NOT MAP, Filled
  categories: [ DoNotMap ]
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetJanitorBomb

- type: entityTable
  id: FillClosetJanitorBomb
  table: !type:AllSelector
    children:
    - id: ClothingHeadHelmetJanitorBombSuit
    - id: ClothingOuterSuitJanitorBomb
